"""empty message

Revision ID: d7fdd7383570
Revises: c033672cf777
Create Date: 2019-08-21 20:36:14.671827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fdd7383570'
down_revision = 'c033672cf777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('origin', sa.String(length=60), nullable=False),
    sa.Column('destination', sa.String(length=60), nullable=False),
    sa.Column('aircraft', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('seats',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('seat_class', sa.String(length=60), nullable=False),
    sa.Column('aircraft', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('flight_sessions',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('flight_id', sa.String(length=22), nullable=True),
    sa.Column('departure', sa.DateTime(), nullable=True),
    sa.Column('arrival', sa.DateTime(), nullable=True),
    sa.Column('delayed', sa.Boolean(), nullable=True),
    sa.Column('canceled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_session_seats',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('flight_session_id', sa.String(length=22), nullable=True),
    sa.Column('seat_id', sa.String(length=22), nullable=True),
    sa.ForeignKeyConstraint(['flight_session_id'], ['flight_sessions.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=22), nullable=True),
    sa.Column('flight_id', sa.String(length=22), nullable=True),
    sa.Column('flight_session_id', sa.String(length=22), nullable=True),
    sa.Column('seat_id', sa.String(length=22), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['flight_session_id'], ['flight_sessions.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['flight_session_seats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('flight_session_seats')
    op.drop_table('flight_sessions')
    op.drop_table('seats')
    op.drop_table('flights')
    # ### end Alembic commands ###
